export enum ImageVariant {
    OPERATOR_SPLASH = "operator-splash",
    ITEM = "item",
    CURRENCY = "currency",
    BUILDING_ICON = "building-icon",
    ITEM_ICON = "item-icon",
    ITEM_ICON_BG = "item-icon-bg",
    BANNER_ICON = "banner-icon",
    BANNER_MINI = "banner-mini",
    EVENT_ICON = "event-icon",
    SKILL_ICON = "skill-icon",
    OPERATOR_PREVIEW = "operator-preview",
    WEAPON_ICON = "weapon-icon",
    WEAPON_BIG = "weapons-big",
    ENEMY_ICON = "enemy-icon",
    EQUIPMENT = "equipment",
    ATTRIBUTE_ICON = "attribute-icon",
    FACILITY_SKILL = "fac-skill",
    OPERATOR_ART = "operator-art",
    OPERATOR_ART_LQ = "operator-art-lq",
    CONTRACT_TAG_ICON = "contract-tag-icon",
    ESSENCE_ICON = "essence-icon",
    ESSENCE_TYPE_ICON = "essence-type-icon",
    OPERATOR_ICON = "operator-icon",
}